### ISSUE TITLE
Error after changing Name

### ISSUE THREAD

**Issue by Architjain12** [atiqsamtia/change_app_package_name#13]
Command I ran:-
flutter pub run change_app_package_name:main SafeHome 

Error:-

AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'SafeHome'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hayato0210-ae** [comment]
Hello.

I had the same error.
In my case, I was able to solve it with the following

\android\app\src\main\kotlin\com\example\sample\MainActivity.kt

old
package com.amuseapp.old

new
package com.amuseapp.new


ERROR:: Unknown Directory structure, both java & kotlin files not found.

If you get the error "ERROR:: Unknown directory structure, both java & kotlin files not found", then MainActivity must not be updated.

Translated with www.DeepL.com/Translator (free version)

**Comment by a-k-o-r-e-d-e** [comment]
> Hello.
> 
> I had the same error.
> In my case, I was able to solve it with the following
> 
> \android\app\src\main\kotlin\com\example\sample\MainActivity.kt
> 
> old
> package com.amuseapp.old
> 
> new
> package com.amuseapp.new
> 
> ERROR:: Unknown Directory structure, both java & kotlin files not found.
> 
> If you get the error "ERROR:: Unknown directory structure, both java & kotlin files not found", then MainActivity must not be updated.
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)




Experiencing this same issue and I don't really understand your fix please

**Comment by kmrosiek** [comment]
If you are getting  `No matching client found for package name` error and you are using Firebase then you can refer to [this answer on stackoverflow](https://stackoverflow.com/a/66767859/5619109)
Regenerating google-services.json for a new package name might help.

**Comment by nbnD** [comment]
Old Package Name: com.mithila.deliveryapp
Updating build.gradle File
Updating Main Manifest file
Updating Debug Manifest file
Updating Profile Manifest file
ERROR:: Unknown Directory structure, both java & kotlin files not found.

Its not working

**Comment by atiqsamtia** [comment]
Changed the mechanism and now it'll work fine irrespective of the directory structure. Fix is LIVE
