### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by brunodmn** [atiqsamtia/change_app_package_name#16]
I ran: flutter pub run change_app_package_name:main com.company.packageName
it throws:
```
Unhandled exception:
Null check operator used on a null value
#0      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:28:41)
<asynchronous suspension>
pub finished with exit code 255
```

**Comment by atiqsamtia** [comment]
Tested this on different projects and I can't reproduce it. Share your gradle.build file it may have some clues for your edge case. reopen the issue when you submit the file.

**Comment by MuhammadAliKust** [comment]
You can resolve this issue by following steps:

1. Go to build.gradle
2. Check applicationId and close it in double quotes if it's under single quote.

Basically we have a check that throw exception:

`    var reg = RegExp('applicationId "(.*)"', caseSensitive: true, multiLine: false);`

According to that, package name should be under double quote.


Booms! Issue will be resolved.
