### ISSUE TITLE
Could not find package "change_app_package_name". Did you forget to add a dependency?

### ISSUE THREAD

**Issue by alishahzad331** [atiqsamtia/change_app_package_name#17]
How to resolve this issues. I tried with multple pub get but didn't resolved

**Comment by rmahmadkhan** [comment]
@alishahzad331 Have you added it in dev_dependencies?

**Comment by atiqsamtia** [comment]
@alishahzad331 

Please use this how-to guide for proper usage. if you still face any issues please post a full log here
![image](https://user-images.githubusercontent.com/5112753/163876424-e480fbd5-9f03-4568-8537-772582b830e0.png)

**Comment by A-Eric-J** [comment]
@atiqsamtia  
I have the same issue:

Could not find package "com.example.application". Did you forget to add a dependency?
pub finished with exit code 65
