### ISSUE TITLE
Will support iOS?

### ISSUE THREAD

**Issue by baoxiehao** [atiqsamtia/change_app_package_name#2]

**Comment by anilk98891** [comment]
ios support ?

**Comment by atiqsamtia** [comment]
iOS support will be coming soon.

**Comment by ajaygautam** [comment]
Any luck with this yet?

**Comment by ajaygautam** [comment]
Actually - this package supports both - android and ios.
Also changes app name.

https://pub.dev/packages/rename

**Comment by atsen-dev** [comment]
Hi, any support for iOs yet ?
I think the package is good but without a complete rename (including android/ios a least) I think a lot of developers will not use it.
The rename package doesn't work always well.

**Comment by dev-thinks** [comment]
but still the pub.dev says it supports all platform.

**Comment by atiqsamtia** [comment]
I do have plans to support iOS. Will be doing it this or next month.

It's a side project and I rarely use it but do contribute to it occasionally, I will be back to full speed soon.

**Comment by pr0xity** [comment]
> Will be doing it this or next month.

Any update to this? :)

**Comment by pr0xity** [comment]
> Will be doing it this or next month.

@atiqsamtia, any update to this? :)

**Comment by azmasamy** [comment]
@atiqsamtia, any update on this?

**Comment by chandrabezzo** [comment]
Have you check [package_rename_plus](https://pub.dev/packages/package_rename_plus)?

**Comment by atiqsamtia** [comment]
iOS support is now LIVE on pub dev version 1.3.0
