### ISSUE TITLE
Manifest merger failed : Package name 'anything' at position AndroidManifest.xml:2:5-22 should contain at least one '.' (dot) character

### ISSUE THREAD

**Issue by wasiflamer** [atiqsamtia/change_app_package_name#23]
i never wanted to change the name manually , i am lazy  , i thought maybe i should use this cool package and be done with it , well kill me lol .  

ps = my flutter app has 'com' in it not sure if it has anything to do with it , it was working fine with that name when i created the old app with the same name so i don't think its a naming convention thing ! , maybe a bug ?  atiq bhai koi hal batayn .

**Comment by atiqsamtia** [comment]
Please file an issue with more info of the BUG so I can better fix that.
