### ISSUE TITLE
"flutter create . -a java --platforms android" error

### ISSUE THREAD

**Issue by X-DCB** [atiqsamtia/change_app_package_name#24]
i'm using the latest version
![image](https://user-images.githubusercontent.com/28706220/197375182-178885cc-927f-4d2f-b86f-b62046e17bf4.png)

kotlin works well but when I used java this error always shows up
I manually fixed the directory tree btw
![image](https://user-images.githubusercontent.com/28706220/197374990-527e8ad4-6208-46ca-ab94-f6607591f47e.png)

**Comment by fatihdurmaz** [comment]
how fixed

**Comment by X-DCB** [comment]
> how fixed

manual renaming of folders

**Comment by atiqsamtia** [comment]
this has been fixed in the latest release
