### ISSUE TITLE
Directory listing failed, path = 'android/app/src/main/kotlin/' 

### ISSUE THREAD

**Issue by fatihdurmaz** [atiqsamtia/change_app_package_name#25]
FileSystemException: Directory listing failed, path = 'android/app/src/main/kotlin/' (OS Error: No such file or directory, errno = 2)

<img width="361" alt="Ekran Resmi 2022-11-14 23 45 27" src="https://user-images.githubusercontent.com/71706970/201762147-8b5c2439-2f6a-4380-8923-f1a385f7b15e.png">

**Comment by v-pavlovskyi** [comment]
https://pub.dev/packages/rename - similar package, works perfect for me

**Comment by v-pavlovskyi** [comment]
+1
