### ISSUE TITLE
IOS Package name not changing.

### ISSUE THREAD

**Issue by wrteam-vimal** [atiqsamtia/change_app_package_name#28]
I just changed the package name using the command "flutter pub run change_app_package_name:main com.new.package.name"

While creating apps using firebase-cli in the firebase Android package name changed properly but the iOS package name is still an older one.

The app package name is proper but iOS bundle ID getting wrong which is an old ID.

**Comment by usamasindhu** [comment]
I'm facing this problem, did anyone find a solution?

**Comment by tvhoan2908** [comment]
I see the code only has update function on android. To update package on ios, you can using xcode.

**Comment by chandrabezzo** [comment]
Hi @wrteam-vimal have you check [package_rename_plus](https://pub.dev/packages/package_rename_plus)?

**Comment by Jaew00Shin** [comment]
I'm facing the same problem in version ^1.2.0
Any update or solution?

**Comment by atiqsamtia** [comment]
iOS support is now added and new version is published on pub dev. 1.3.0
