### ISSUE TITLE
Text inside comment got changed

### ISSUE THREAD

**Issue by maBarabas** [atiqsamtia/change_app_package_name#29]
`<!-- https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html -->`

is changed to

`<!-- https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package="com.example">`

This line should not change.

**Comment by adrinr** [comment]
I opened a PR to fix this issue ages ago: https://github.com/atiqsamtia/change_app_package_name/pull/21

**Comment by chimura** [comment]
Isn't this solved yet?

**Comment by atiqsamtia** [comment]
It is fixed by #21 and merged
