### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by fadlishrd** [atiqsamtia/change_app_package_name#30]
Deprecated. Use `dart run` instead.
Unhandled exception:
Null check operator used on a null value
#0      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:29:41)
<asynchronous suspension>

**Comment by chandrabezzo** [comment]
Hi @atiqsamtia have you check [package_rename_plus](https://pub.dev/packages/package_rename_plus)?

**Comment by atiqsamtia** [comment]
This has been fixed in latest commit. If you reencounter this issue, please reopen the issue with `android/app/build.gradle` file.
