### ISSUE TITLE
Unhandled exception: PathNotFoundException: Directory listing failed, path = 'android/app/src/main/kotlin\*' (OS Error: The system cannot find the path specified. , errno = 3)

### ISSUE THREAD

**Issue by MaheshPhuyal02** [atiqsamtia/change_app_package_name#34]
If there is no any kotlin folder, it's throwing error: 
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'android/app/src/main/kotlin\*' (OS Error: The system cannot find the path specified.
, errno = 3)

Screenshot of the error: 
![image](https://github.com/atiqsamtia/change_app_package_name/assets/94818265/3c4056eb-d30c-47f0-b54d-dffecb89f8d3)

**Comment by jeffersonmello** [comment]
i have same error

**Comment by jeffersonmello** [comment]
I created a Kotlin folder inside the main folder, and it worked.

**Comment by atiqsamtia** [comment]
Are you using the latest version of this package? This sequence of output should not occur in the latest version and I previously added checks to handle these scenarios where kotlin directory does not exist.
