### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by nitesharma** [atiqsamtia/change_app_package_name#36]
nitesharma@Niteshs-MacBook-Pro monkoodog_panel_mobile % flutter pub run change_app_package_name:main com.monkoodog.panel
Deprecated. Use `dart run` instead.
Resolving dependencies... 
Downloading packages... 
Got dependencies.
Building package executable... 
Built change_app_package_name:main.
Unhandled exception:
Null check operator used on a null value
#0      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:29:41)
<asynchronous suspension>

**Comment by Aksoyhlc** [comment]
You can use the edited version below.

  ```
change_app_package_name:
    git: https://github.com/Aksoyhlc/change_app_package_name.git
```

**Comment by arioul89** [comment]
Hi @Aksoyhlc 

Problem persists

**Comment by Aksoyhlc** [comment]
> Hi @Aksoyhlc 
> 
> Problem persists

Hello, can you share the android/app/build.gradle file?

**Comment by atiqsamtia** [comment]
There seems to be an issue with build.gradle file.or maybe you created a project with flutter 3.22.0

Please update to the latest version and test again, otherwise you can reopen this issue with `android/app/build.gradle`  file contents for me to debug.

Thanks @Aksoyhlc for the assist
