### ISSUE TITLE
Not Working on Flutter 3.22.0

### ISSUE THREAD

**Issue by nahidnsu152** [atiqsamtia/change_app_package_name#37]
In flutter latest update (3.22.0), the package name change command gives an error. 

Building package executable... 
Built change_app_package_name:main.
Unhandled exception:
Null check operator used on a null value
#0      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:29:41)
<asynchronous suspension>

**Comment by Aksoyhlc** [comment]
@nahidnsu152 
You can use the edited version below.

  ```
change_app_package_name:
    git: https://github.com/Aksoyhlc/change_app_package_name.git
```

**Comment by adarshneeds** [comment]
@Aksoyhlc It's work!! Thanks

**Comment by atiqsamtia** [comment]
The latest release is going to support both 3.22.0 and earlier versions. Thanks @Aksoyhlc
