### ISSUE TITLE
The method 'group' was called on null.

### ISSUE THREAD

**Issue by jayeshpansheriya** [atiqsamtia/change_app_package_name#4]
`jj@ind836 Web2App % flutter pub run change_app_package_name:main com.new.package.name
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:23:41)
<asynchronous suspension>
#2      ChangeAppPackageName.start (package:change_app_package_name/change_app_package_name.dart:12:40)
#3      main (file:///Users/indianic/development/flutter/.pub-cache/hosted/pub.dartlang.org/change_app_package_name-0.1.2/bin/main.dart:4:24)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

**Comment by atiqsamtia** [comment]
FIxed alongside #6
