### ISSUE TITLE
[Question] after git clone a project

### ISSUE THREAD

**Issue by scheung38** [atiqsamtia/change_app_package_name#5]
git clone project
flutter pub run change_app_package_name:main com.example.dev.frontend
flutter run

the above can run no problem

But:

git clone project myapp
flutter pub run change_app_package_name:main com.example.dev.frontend
flutter run <--- ERROR still looking for previous package

**Comment by atiqsamtia** [comment]
It checks the old package name from your existing build.gradle file. It is not dependent on directory where you put the flutter project. 

Make sure to run `flutter pub get` after git clone and change your directory on CMD to the one where you cloned the project.
