### ISSUE TITLE
Invalid argument(s) (input): Must not be null

### ISSUE THREAD

**Issue by CivelXu** [atiqsamtia/change_app_package_name#6]
Unhandled exception:
Invalid argument(s) (input): Must not be null
#0      _RegExp.firstMatch (dart:core-patch/regexp_patch.dart:221:24)
#1      AndroidRenameSteps.process (package:change_app_package_name/android_rename_steps.dart:23:20)
<asynchronous suspension>
#2      ChangeAppPackageName.start (package:change_app_package_name/change_app_package_name.dart:12:40)
#3      main (file:///Users/civelxu/.pub-cache/hosted/pub.flutter-io.cn/change_app_package_name-0.1.2/bin/main.dart:4:24)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by atiqsamtia** [comment]
Fixed. Please check latest version
